name: build_portable

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-2022
          - os: macos-11

    runs-on: ${{ matrix.os }}

    steps:

      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: 'true'

      # - name: Install System OpenJDK 8
      #   run: |
      #     sudo apt-get install -y openjdk-8-jdk
      #     sudo apt-get install -y openjdk-8-jre

      # - name: Install System OpenJDK 17
      #   run: |
      #     sudo apt-get install -y openjdk-17-jdk
      #     sudo apt-get install -y openjdk-17-jre

      # - name: Show jvm directories
      #   shell: bash
      #   run: |
      #     set +x
      #     ls -alhR /usr/lib/jvm/java-8-openjdk-amd64
      #     ls -alhR /usr/lib/jvm/java-17-openjdk-amd64

      # - name: Show alternatives
      #   shell: bash
      #   run: |
      #     set -x
      #     # update-java-alternatives --list
      #     sudo update-java-alternatives --set java-1.17.0-openjdk-amd64

      # - name: Set up MinGW
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x86

      # - name: Install Strawberry
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install strawberryperl -y --force --x86

      # - name: Find
      #   if: runner.os == 'Windows'
      #   run: |
      #     Get-Childitem –Path C:\Strawberry -Include *i686* -File -Recurse -ErrorAction SilentlyContinue

      # - name: Find
      #   if: runner.os == 'Windows'
      #   shell: bash
      #   run: |
      #     ls -alhR C:/Strawberry

      - name: Download OpenSSL libs on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          python -m pip install aqtinstall==2.0.5
          python -m aqt install-tool -O "${{ github.workspace }}\Qt\" windows desktop tools_openssl_x86

      - name: Do something else
        shell: bash
        run: |
          echo "Doing something"

      - name: Install OpenSSL libs on Windows
        if: runner.os == 'Windows'
        run: |
          mkdir install
          copy "${{ github.workspace }}\Qt\Tools\OpenSSL\Win_x86\bin\libssl-1_1.dll" "${{ github.workspace }}\install\"
          copy "${{ github.workspace }}\Qt\Tools\OpenSSL\Win_x86\bin\libcrypto-1_1.dll" "${{ github.workspace }}\install\"
